//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EADP_Web_Dev.Code.Medicine
{
    public partial class MedCart
    {
        public int ID { get; set; }
        public string CilentID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public bool IsInCart { get; set; }
    }
}
