//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EADP_Web_Dev.Code.Medicine
{
    public partial class Medicine
    {
        public int medID { get; set; }
        public string medName { get; set; }
        public string medDesc { get; set; }
        public Nullable<int> medQuantity { get; set; }
        public Nullable<double> medPrice { get; set; }
    }
}
